### ISSUE TITLE
lv2lint fails on lv2 plugins

### ISSUE THREAD

**Issue by dvzrv** [michaelwillis/dragonfly-reverb#65]
Hi! When packaging 3.0.0 for Arch Linux, I ran [lv2lint](https://open-music-kontrollers.ch/lv2/lv2lint/#) on the plugins:

```
LV2_PATH="${PWD}/bin" lv2lint "https://github.com/michaelwillis/dragonfly-reverb"
```

Unfortunately it fails, as e.g. all but DragonflyHallReverb lack a URI. Some of the issues might be due to DPF:

```
lv2lint 0.3.27
Copyright (c) 2016-2020 Hanspeter Portner (dev@open-music-kontrollers.ch)
Released under Artistic License 2.0 by Open Music Kontrollers
error: failed to open file /build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyEarlyReflections-vst.so/manifest.ttl (Not a directory)
lilv_world_load_file(): error: Error loading file `file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyEarlyReflections-vst.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyEarlyReflections-vst.so/manifest.ttl
error: failed to open file /build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyEarlyReflections/manifest.ttl (Not a directory)
lilv_world_load_file(): error: Error loading file `file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyEarlyReflections/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyEarlyReflections/manifest.ttl
error: failed to open file /build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyPlateReverb-vst.so/manifest.ttl (Not a directory)
lilv_world_load_file(): error: Error loading file `file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyPlateReverb-vst.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyPlateReverb-vst.so/manifest.ttl
error: failed to open file /build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyPlateReverb/manifest.ttl (Not a directory)
lilv_world_load_file(): error: Error loading file `file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyPlateReverb/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyPlateReverb/manifest.ttl
error: failed to open file /build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyRoomReverb-vst.so/manifest.ttl (Not a directory)
lilv_world_load_file(): error: Error loading file `file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyRoomReverb-vst.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyRoomReverb-vst.so/manifest.ttl
error: failed to open file /build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyRoomReverb/manifest.ttl (Not a directory)
lilv_world_load_file(): error: Error loading file `file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyRoomReverb/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyRoomReverb/manifest.ttl
error: failed to open file /build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyHallReverb-vst.so/manifest.ttl (Not a directory)
lilv_world_load_file(): error: Error loading file `file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyHallReverb-vst.so/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyHallReverb-vst.so/manifest.ttl
error: failed to open file /build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyHallReverb/manifest.ttl (Not a directory)
lilv_world_load_file(): error: Error loading file `file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyHallReverb/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///build/dragonfly-reverb/src/dragonfly-reverb-3.0.0/bin/DragonflyHallReverb/manifest.ttl
Host does not provide nominalBlockLength or maxBlockLength options
<https://github.com/michaelwillis/dragonfly-reverb>
    [FAIL]  Symbols
              binary exports superfluous globally visible symbols:
                * lv2_generate_ttl
              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
    [WARN]  Linking
              binary links to non-whitelisted shared libraries:
                * libfreeverb3.so.3
              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
    [FAIL]  License
              doap:license not a URI
              seeAlso: <http://usefulinc.com/ns/doap#license>
    [WARN]  Author Email
              foaf:email not found
              seeAlso: <http://lv2plug.in/ns/lv2core#project>
    [WARN]  Class
              type is just lv2:Plugin
              seeAlso: <http://lv2plug.in/ns/lv2core#Plugin>
    [FAIL]  Worker
              work:interface has no 'work_response' function
              seeAlso: <http://lv2plug.in/ns/ext/worker#interface>
  {9 : size}
    [FAIL]  Units
              units_unit not a URI or object
              seeAlso: <http://lv2plug.in/ns/extensions/units#unit>
  {15 : low_mult}
    [FAIL]  Units
              units_unit not a URI or object
              seeAlso: <http://lv2plug.in/ns/extensions/units#unit>
  {18 : high_mult}
    [FAIL]  Units
              units_unit not a URI or object
              seeAlso: <http://lv2plug.in/ns/extensions/units#unit>
  <https://github.com/michaelwillis/dragonfly-reverb#UI>
    [FAIL]  Idle Interface
              lv2:feature ui:idleInterface missing
              seeAlso: <http://lv2plug.in/ns/extensions/ui#idleInterface>
    [FAIL]  Resize Interface
              lv2:extensionData ui:resize missing
              seeAlso: <http://lv2plug.in/ns/extensions/ui#resize>
    [WARN]  Toolkit
              usage of official external UI is discouraged
              seeAlso: <http://lv2plug.in/ns/extensions/ui#showInterface>
```

**Comment by falkTX** [comment]
Note some of those are fixed in latest DPF.

**Comment by dvzrv** [comment]
With 3.2.3 the failures have been reduced, but there are still some:

```
lv2lint 0.8.0
Copyright (c) 2016-2020 Hanspeter Portner (dev@open-music-kontrollers.ch)
Released under Artistic License 2.0 by Open Music Kontrollers
Host does not provide nominalBlockLength or maxBlockLength options
<https://github.com/michaelwillis/dragonfly-reverb>
    [FAIL]  Plugin Symbols
              binary exports superfluous globally visible symbols:
                * lv2_generate_ttl
              seeAlso: <http://lv2plug.in/ns/lv2core#binary>
    [FAIL]  Plugin License
              doap:license not a URI
              seeAlso: <http://usefulinc.com/ns/doap#license>
    [WARN]  Plugin Author Email
              foaf:mbox not found
              seeAlso: <http://lv2plug.in/ns/lv2core#project>
```

**Comment by falkTX** [comment]
Those are very minor now.

The plugin symbols is expected, we always have an extra symbol for lv2 data export in DPF and juce plugins.
License is a tricky one, to be handled by DPF later.
Author email is something not exposed in DPF at the moment, and it is not mandatory. Actually would prefer to leave that out

**Comment by dvzrv** [comment]
@falkTX are there any changes to DPF that address the plugin license uri?
I have now ignored `lv2_generate_ttl`, but the Plugin License issue remains.

**Comment by falkTX** [comment]
no changes there yet. I meant to start work on dpf already, but vital source code happened and got my attention :P

**Comment by michaelwillis** [comment]
@dvzrv, Does 91d187a339f68005288d82940e0639fa4e86e0c1 fix this?

**Comment by dvzrv** [comment]
@michaelwillis yes! thank you! :)
